theme: jekyll-theme-minimal
title: Shuchang (Orly) Liu
description: "Supply Chain analyst with 1+ year work experience in inventory, procurement, and operations management."
logo: /images/profile.png
show_downloads: false
