theme: jekyll-theme-minimal
title: Shuchang (Orly) Liu
description: "Supply chain data analyst with hands-on experience in inventory, procurement, and logistics management. M.S. in Global Supply Chain Management, USC Marshall, expected to graduate in December 2026."
logo: /images/profile.png
show_downloads: false
