theme: jekyll-theme-minimal
title: Shuchang (Orly) Liu
description: "Supply chain data analyst with work experience in inventory, procurement, and logistics management. Master of Science in Global Supply Chain Management, USC Marshall, graduating in December 2026."
logo: /images/profile.png
show_downloads: false
